### ISSUE TITLE
Getting started and a weird error message in machine.py

### ISSUE THREAD

**Issue by perbu** [tflander/esp32-machine-emulator#1]
Hi!

I was very happy to see the work you've put down here. I've been frustrated with the difficulties of doing TDD with Micropython. I feel like I've been spoiled with pytest.

I'm still a bit new to Micropython but I'm struggling getting your module to work. When I fire up micropython after upip installing your module I try to import 'machine' and it fails.

```
$ micropython   
MicroPython v1.12 on 2020-01-11; darwin version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> import machine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "machine.py", line 69, in <module>
AttributeError: 'module' object has no attribute 'sleep_us'
```

This is a weird message as line 69 looks resonable:
```
time.sleep_us = sleep_us_for_monkey_patching
```

This leads me thinking that I'm missing something fundamental.

PS: I'll be happy to contribute a users guide if you want to. I just need to get to the place where I can use the module first. :-)

All the best,

Per.

**Comment by perbu** [comment]
Of course the moment I posted this I found that if I import time before I'm importing machine the problem goes away. 

It would still be useful to see some more details on invocation. I'd love to see how you test your project, or at least how you're able to run the example tests in the repo. I'm guessing you have some shell script that sets MICROPYPATH and such.
